USE [master]
GO

/****** Object:  Database [TechnossusDb]    Script Date: 6/19/2018 3:28:02 PM ******/
CREATE DATABASE [TechnossusDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TechnossusDb', FILENAME = N'E:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TechnossusDb.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TechnossusDb_log', FILENAME = N'E:\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\TechnossusDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TechnossusDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TechnossusDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TechnossusDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TechnossusDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TechnossusDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TechnossusDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TechnossusDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TechnossusDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TechnossusDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TechnossusDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TechnossusDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TechnossusDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TechnossusDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TechnossusDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TechnossusDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TechnossusDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TechnossusDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TechnossusDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TechnossusDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TechnossusDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TechnossusDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TechnossusDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TechnossusDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TechnossusDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TechnossusDb] SET RECOVERY FULL 
GO

ALTER DATABASE [TechnossusDb] SET  MULTI_USER 
GO

ALTER DATABASE [TechnossusDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TechnossusDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TechnossusDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TechnossusDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TechnossusDb] SET  READ_WRITE 
GO


